trigger:
  - main

pool:
  name: 'Default'  # Update this to the name of your self-hosted agent pool

steps:
  - task: UseNode@1
    inputs:
      version: '12.x'
  - script: npm install
    displayName: 'Install dependencies'
  - script: npm run build
    displayName: 'Build project'
  - script: npm test
    displayName: 'Run tests'
